const levels = {
    level0: {
        name: 'Level 0',
        data: [],
        next: 'level1',
        startX: 100,
        startY: 100,
        background: {
            r: 250,
            g: 200,
            b: 200,
        },
    },
    level1: {
        name: 'Level 1',
        data: mapLevel1,
        next: 'level2',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 200,
        },
    },
    level2: {
        name: 'Level 2',
        data: mapLevel2,
        next: 'level3',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 200,
            b: 250,
        },
    },
    level3: {
        name: 'Level 3',
        data: mapLevel3,
        next: 'level4',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level4: {
        name: 'Level 4',
        data: mapLevel4,
        next: 'level5',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level5: {
        name: 'Level 5',
        data: mapLevel5,
        next: 'level6',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level6: {
        name: 'Level 6',
        data: mapLevel6,
        next: 'level7',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level7: {
        name: 'Level 7',
        data: mapLevel7,
        next: 'level8',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level8: {
        name: 'Level 8',
        data: mapLevel8,
        next: 'level9',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level9: {
        name: 'Level 9',
        data: mapLevel9,
        next: 'level10',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
    level10: {
        name: 'Level 10',
        data: mapLevel10,
        next: 'level1',
        startX: 80,
        startY: 375,
        background: {
            r: 200,
            g: 250,
            b: 250,
        },
    },
}